<a href="https://colab.research.google.com/github/Alexiserges/Word-embedding-Techniques-with-LSTM/blob/main/Word_embedding_Techniques_with_LSTM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#The attached files are my daily lesson plan of 12/07/2022

#Thank you.

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 5.7 kB/s 
     |████████████████████████████████| 5.8 MB 41.7 MB/s 
     |████████████████████████████████| 1.6 MB 50.2 MB/s 
     |████████████████████████████████| 438 kB 71.7 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [3]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=['The word is a better place',
     'Marvel series is my favourite movie',
     'I like DC movies',
    'The cat is eating the food',
     'Tom and jerry is my favourite movie',
     'Python is my suitable programming language',
     'I want to build my network in data science']

In [6]:
sent

['The word is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'The cat is eating the food',
 'Tom and jerry is my favourite movie',
 'Python is my suitable programming language',
 'I want to build my network in data science']

In [7]:
### Vocabulary size
voc_size=800

###One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[227, 76, 530, 314, 689, 670], [750, 220, 530, 738, 255, 53], [14, 727, 159, 17], [227, 796, 530, 595, 227, 788], [619, 269, 309, 530, 738, 255, 53], [728, 530, 738, 123, 275, 285], [14, 269, 384, 712, 738, 467, 511, 244, 410]]


###Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [13]:
## pre padding
sent_length=9
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0 227  76 530 314 689 670]
 [  0   0   0 750 220 530 738 255  53]
 [  0   0   0   0   0  14 727 159  17]
 [  0   0   0 227 796 530 595 227 788]
 [  0   0 619 269 309 530 738 255  53]
 [  0   0   0 728 530 738 123 275 285]
 [ 14 269 384 712 738 467 511 244 410]]


In [14]:
## 10 feature dimesnions
dim=10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 9, 10)             8000      
                                                                 
Total params: 8,000
Trainable params: 8,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
##'The word is a better place',
embedded_docs[0]

array([  0,   0,   0, 227,  76, 530, 314, 689, 670], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 102ms/step


array([[-0.035059  ,  0.04403411, -0.00231515,  0.01556463,  0.01342452,
        -0.02428705,  0.04382536, -0.00162061,  0.0293929 ,  0.03303542],
       [-0.035059  ,  0.04403411, -0.00231515,  0.01556463,  0.01342452,
        -0.02428705,  0.04382536, -0.00162061,  0.0293929 ,  0.03303542],
       [-0.035059  ,  0.04403411, -0.00231515,  0.01556463,  0.01342452,
        -0.02428705,  0.04382536, -0.00162061,  0.0293929 ,  0.03303542],
       [-0.03562839,  0.00521716,  0.0192288 , -0.01612967,  0.04289402,
        -0.00330611,  0.04157707, -0.03659555, -0.00373067, -0.00627972],
       [-0.01198177, -0.00477816, -0.04007648, -0.01684242, -0.03810278,
        -0.04799842, -0.0241154 , -0.0251549 , -0.02634882, -0.02636769],
       [ 0.04490879,  0.01277279,  0.03271898,  0.03500445,  0.02245596,
        -0.04923625,  0.03671182, -0.04704349, -0.04409503,  0.03213454],
       [-0.03812807, -0.04719676, -0.04788455, -0.03579825, -0.02163421,
         0.00143287,  0.04497642,  0.0415324 

In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 37ms/step
[[[-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452
   -0.02428705  0.04382536 -0.00162061  0.0293929   0.03303542]
  [-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452
   -0.02428705  0.04382536 -0.00162061  0.0293929   0.03303542]
  [-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452
   -0.02428705  0.04382536 -0.00162061  0.0293929   0.03303542]
  [-0.03562839  0.00521716  0.0192288  -0.01612967  0.04289402
   -0.00330611  0.04157707 -0.03659555 -0.00373067 -0.00627972]
  [-0.01198177 -0.00477816 -0.04007648 -0.01684242 -0.03810278
   -0.04799842 -0.0241154  -0.0251549  -0.02634882 -0.02636769]
  [ 0.04490879  0.01277279  0.03271898  0.03500445  0.02245596
   -0.04923625  0.03671182 -0.04704349 -0.04409503  0.03213454]
  [-0.03812807 -0.04719676 -0.04788455 -0.03579825 -0.02163421
    0.00143287  0.04497642  0.0415324   0.03567794  0.01500242]
  [ 0.0226511   0.00958524 -0.02014425  0.03147065  0.02279

In [20]:
embedded_docs[0]

array([  0,   0,   0, 227,  76, 530, 314, 689, 670], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 17ms/step
[[-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452 -0.02428705
   0.04382536 -0.00162061  0.0293929   0.03303542]
 [-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452 -0.02428705
   0.04382536 -0.00162061  0.0293929   0.03303542]
 [-0.035059    0.04403411 -0.00231515  0.01556463  0.01342452 -0.02428705
   0.04382536 -0.00162061  0.0293929   0.03303542]
 [-0.03562839  0.00521716  0.0192288  -0.01612967  0.04289402 -0.00330611
   0.04157707 -0.03659555 -0.00373067 -0.00627972]
 [-0.01198177 -0.00477816 -0.04007648 -0.01684242 -0.03810278 -0.04799842
  -0.0241154  -0.0251549  -0.02634882 -0.02636769]
 [ 0.04490879  0.01277279  0.03271898  0.03500445  0.02245596 -0.04923625
   0.03671182 -0.04704349 -0.04409503  0.03213454]
 [-0.03812807 -0.04719676 -0.04788455 -0.03579825 -0.02163421  0.00143287
   0.04497642  0.0415324   0.03567794  0.01500242]
 [ 0.0226511   0.00958524 -0.02014425  0.03147065  0.02279112  0.03906653